=== luismorais14/PEI_2425/XML+XSD/RegistoClinico.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.MedSync.pt/RegistoClinico"
    elementFormDefault="qualified">
    
    <xs:element name="RelatorioHospital">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Hospital">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CodHospital" type="xs:string"/>
                            <xs:element name="NomeHospital" type="xs:string"/>
                            <xs:element name="MoradaHospital" type="xs:string"/>
                            <xs:element name="MesRelatorio" type="xs:string"/>
                            <xs:element name="AnoFiscalRelatorio" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="ListaPacientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Paciente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="NomeCompleto" type="xs:string"/>
                                        <xs:element name="DataNascimento" type="xs:string"/>
                                        <xs:element name="Genero" type="xs:string"/>
                                        <xs:element name="ID" type="xs:string"/>
                                        <xs:element name="Contacto">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Telefone" type="xs:string" minOccurs="0"/>
                                                    <xs:element name="Email" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="TipoPaciente">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Novo"/>
                                                    <xs:enumeration value="Regular"/>
                                                    <xs:enumeration value="CrÃ´nico"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="RegistosClinicos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Registo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="CodAtendimento" type="xs:string"/>
                                        <xs:element name="Data" type="xs:dateTime"/>
                                        <xs:element name="Especialidade" type="xs:string"/>
                                        
                                        <xs:element name="Diagnosticos" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Diagnostico" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="TipoDiagnostico" type="xs:string"/>
                                                                <xs:element name="CodigoCID10" type="xs:string"/>
                                                                <xs:element name="DescricaoDiagnostico" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        
                                        <xs:element name="Tratamentos" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Tratamento" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="ID" type="xs:int"/>
                                                                <xs:element name="IdRegistoClinico" type="xs:int"/>
                                                                <xs:element name="Tipo" type="xs:string"/>
                                                                <xs:element name="Realizado">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:string">
                                                                            <xs:enumeration value="Sim"/>
                                                                            <xs:enumeration value="Nao"/>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        
                                        <xs:element name="ID_Profissional" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="ResumoMensal">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PacientesAtendidos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="PorGenero" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded">
                                                    <xs:element name="Genero" type="xs:string"/>
                                                    <xs:element name="Total" type="xs:int"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="PorFaixaEtaria" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded">
                                                    <xs:element name="FaixaEtaria" type="xs:string"/>
                                                    <xs:element name="Total" type="xs:int"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="CasosPorEspecialidade" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded">
                                        <xs:element name="Especialidade" type="xs:string"/>
                                        <xs:element name="Total" type="xs:int"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="TratamentosRealizados" type="xs:int"/>
                            <xs:element name="NumeroCondicoesCronicas" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== luismorais14/PEI_2425/XML+XSD/relatorio_registo_clinico.xml
<RelatorioHospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="RegistoClinico.xsd"
    xsi:schemaLocation="http://www.MedSync.pt/RegistoClinico RegistoClinico.xsd">
    <Hospital>
        <CodHospital>H123</CodHospital>
        <NomeHospital>Hospital Felgueiras</NomeHospital>
        <MoradaHospital>Rua da ESTGf, 11</MoradaHospital>
        <MesRelatorio>2</MesRelatorio>
        <AnoFiscalRelatorio>2023</AnoFiscalRelatorio>
    </Hospital>
    <ListaPacientes>
        <Paciente>
            <NomeCompleto>Michael Lewis</NomeCompleto>
            <DataNascimento>1982-03-13T00:00:00.000Z</DataNascimento>
            <Genero>F</Genero>
            <ID>3703</ID>
            <Contacto>
                <Telefone>não fornecido</Telefone>
                <Email>desconhecido</Email>
            </Contacto>
            <TipoPaciente>Crônico</TipoPaciente>
        </Paciente>
        <Paciente>
            <NomeCompleto>Maria Soto</NomeCompleto>
            <DataNascimento>1960-03-10T00:00:00.000Z</DataNascimento>
            <Genero>F</Genero>
            <ID>5710</ID>
            <Contacto>
                <Telefone>não fornecido</Telefone>
                <Email>desconhecido</Email>
            </Contacto>
            <TipoPaciente>Crônico</TipoPaciente>
        </Paciente>
        <Paciente>
            <NomeCompleto>Samuel Barnett</NomeCompleto>
            <DataNascimento>1972-03-17T00:00:00.000Z</DataNascimento>
            <Genero>M</Genero>
            <ID>13249</ID>
            <Contacto>
                <Telefone>+1-254-984-4581</Telefone>
                <Email>desconhecido</Email>
            </Contacto>
            <TipoPaciente>Crônico</TipoPaciente>
        </Paciente>
        <Paciente>
            <NomeCompleto>Robert Simmons</NomeCompleto>
            <DataNascimento>1973-04-14T00:00:00.000Z</DataNascimento>
            <Genero>F</Genero>
            <ID>2846</ID>
            <Contacto>
                <Telefone>001-996-275-9109x435</Telefone>
                <Email>tfisher@example.com</Email>
            </Contacto>
            <TipoPaciente>Crônico</TipoPaciente>
        </Paciente>
        <Paciente>
            <NomeCompleto>Jennifer Woods</NomeCompleto>
            <DataNascimento>1963-02-20T00:00:00.000Z</DataNascimento>
            <Genero>M</Genero>
            <ID>8404</ID>
            <Contacto>
                <Telefone>807.567.3087</Telefone>
                <Email>heather70@example.org</Email>
            </Contacto>
            <TipoPaciente>Crônico</TipoPaciente>
        </Paciente>
    </ListaPacientes>
    <RegistosClinicos>
        <Registo>
            <CodAtendimento>20</CodAtendimento>
            <Data>2023-02-24T00:00:00.000Z</Data>
            <Especialidade>Ortopedista</Especialidade>
            <Diagnosticos>
                <Diagnostico>
                    <TipoDiagnostico>Principal</TipoDiagnostico>
                    <CodigoCID10>Q20</CodigoCID10>
                    <DescricaoDiagnostico>Malformações congênitas do coração</DescricaoDiagnostico>
                </Diagnostico>
            </Diagnosticos>
            <Tratamentos>
                <Tratamento>
                    <ID>413671</ID>
                    <IdRegistoClinico>20</IdRegistoClinico>
                    <Tipo>Exame de colesterol</Tipo>
                    <Realizado>Nao</Realizado>
                </Tratamento>
            </Tratamentos>
            <ID_Profissional>72</ID_Profissional>
        </Registo>
        <Registo>
            <CodAtendimento>55</CodAtendimento>
            <Data>2023-02-18T00:00:00.000Z</Data>
            <Especialidade>Dermatologista</Especialidade>
            <Diagnosticos>
                <Diagnostico>
                    <TipoDiagnostico>Principal</TipoDiagnostico>
                    <CodigoCID10>C34</CodigoCID10>
                    <DescricaoDiagnostico>Neoplasia maligna dos brônquios e dos pulmões</DescricaoDiagnostico>
                </Diagnostico>
            </Diagnosticos>
            <Tratamentos>
                <Tratamento>
                    <ID>39966</ID>
                    <IdRegistoClinico>55</IdRegistoClinico>
                    <Tipo>Nebulização</Tipo>
                    <Realizado>Sim</Realizado>
                </Tratamento>
            </Tratamentos>
            <ID_Profissional>67</ID_Profissional>
        </Registo>
        <Registo>
            <CodAtendimento>69</CodAtendimento>
            <Data>2023-02-15T00:00:00.000Z</Data>
            <Especialidade>Cardiologista</Especialidade>
            <Diagnosticos>
                <Diagnostico>
                    <TipoDiagnostico>Principal</TipoDiagnostico>
                    <CodigoCID10>L20</CodigoCID10>
                    <DescricaoDiagnostico>Dermatite atópica</DescricaoDiagnostico>
                </Diagnostico>
                <Diagnostico>
                    <TipoDiagnostico>Secundario</TipoDiagnostico>
                    <CodigoCID10>Q20</CodigoCID10>
                    <DescricaoDiagnostico>Malformações congênitas do coração</DescricaoDiagnostico>
                </Diagnostico>
                <Diagnostico>
                    <TipoDiagnostico>Secundario</TipoDiagnostico>
                    <CodigoCID10>N39</CodigoCID10>
                    <DescricaoDiagnostico>Outros distúrbios do trato urinário</DescricaoDiagnostico>
                </Diagnostico>
            </Diagnosticos>
            <Tratamentos>
                <Tratamento>
                    <ID>50693</ID>
                    <IdRegistoClinico>69</IdRegistoClinico>
                    <Tipo>Fisioterapia</Tipo>
                    <Realizado>Sim</Realizado>
                </Tratamento>
                <Tratamento>
                    <ID>124836</ID>
                    <IdRegistoClinico>69</IdRegistoClinico>
                    <Tipo>Remoção de verrugas</Tipo>
                    <Realizado>Sim</Realizado>
                </Tratamento>
                <Tratamento>
                    <ID>188947</ID>
                    <IdRegistoClinico>69</IdRegistoClinico>
                    <Tipo>Terapia respiratória</Tipo>
                    <Realizado>Sim</Realizado>
                </Tratamento>
                <Tratamento>
                    <ID>223362</ID>
                    <IdRegistoClinico>69</IdRegistoClinico>
                    <Tipo>Curativo de ferida cirúrgica</Tipo>
                    <Realizado>Sim</Realizado>
                </Tratamento>
                <Tratamento>
                    <ID>362393</ID>
                    <IdRegistoClinico>69</IdRegistoClinico>
                    <Tipo>Vacinação</Tipo>
                    <Realizado>Sim</Realizado>
                </Tratamento>
            </Tratamentos>
            <ID_Profissional>166</ID_Profissional>
        </Registo>
        <Registo>
            <CodAtendimento>79</CodAtendimento>
            <Data>2023-02-08T00:00:00.000Z</Data>
            <Especialidade>Dermatologista</Especialidade>
            <Diagnosticos>
                <Diagnostico>
                    <TipoDiagnostico>Principal</TipoDiagnostico>
                    <CodigoCID10>C34</CodigoCID10>
                    <DescricaoDiagnostico>Neoplasia maligna dos brônquios e dos pulmões</DescricaoDiagnostico>
                </Diagnostico>
                <Diagnostico>
                    <TipoDiagnostico>Secundario</TipoDiagnostico>
                    <CodigoCID10>E11</CodigoCID10>
                    <DescricaoDiagnostico>Diabetes mellitus não insulinodependente</DescricaoDiagnostico>
                </Diagnostico>
                <Diagnostico>
                    <TipoDiagnostico>Secundario</TipoDiagnostico>
                    <CodigoCID10>F32</CodigoCID10>
                    <DescricaoDiagnostico>Episódios depressivos</DescricaoDiagnostico>
                </Diagnostico>
                <Diagnostico>
                    <TipoDiagnostico>Secundario</TipoDiagnostico>
                    <CodigoCID10>O80</CodigoCID10>
                    <DescricaoDiagnostico>Parto único espontâneo</DescricaoDiagnostico>
                </Diagnostico>
            </Diagnosticos>
            <Tratamentos/>
            <ID_Profissional>126</ID_Profissional>
        </Registo>
        <Registo>
            <CodAtendimento>80</CodAtendimento>
            <Data>2023-02-20T00:00:00.000Z</Data>
            <Especialidade>Dermatologista</Especialidade>
            <Diagnosticos>
                <Diagnostico>
                    <TipoDiagnostico>Principal</TipoDiagnostico>
                    <CodigoCID10>B20</CodigoCID10>
                    <DescricaoDiagnostico>Doença pelo vírus da imunodeficiência humana [HIV] resultante em doenças infecciosas e parasitárias</DescricaoDiagnostico>
                </Diagnostico>
            </Diagnosticos>
            <Tratamentos>
                <Tratamento>
                    <ID>408492</ID>
                    <IdRegistoClinico>80</IdRegistoClinico>
                    <Tipo>Ressonância magnética</Tipo>
                    <Realizado>Nao</Realizado>
                </Tratamento>
            </Tratamentos>
            <ID_Profissional>61</ID_Profissional>
        </Registo>
    </RegistosClinicos>
    <ResumoMensal>
        <PacientesAtendidos>
            <PorGenero>
                <Genero>F</Genero>
                <Total>5257</Total>
                <Genero>M</Genero>
                <Total>5441</Total>
            </PorGenero>
            <PorFaixaEtaria>
                <FaixaEtaria>0-17</FaixaEtaria>
                <Total>705</Total>
                <FaixaEtaria>18-29</FaixaEtaria>
                <Total>2083</Total>
                <FaixaEtaria>30-39</FaixaEtaria>
                <Total>1766</Total>
