=== luismorais14/PEI_2425/XML+XSD/Transferencias.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.MedSync.pt/Transferencias"
    elementFormDefault="qualified">

    <xs:element name="Relatorio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="HospitalDestino" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="NomeHospital" type="xs:string"/>
                            <xs:element name="RegistosTransferencias" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="CodigoPaciente" type="xs:string"/>
                                        <xs:element name="DataTransferencia" type="xs:string"/>
                                        <xs:element name="Motivo" type="xs:string"/>
                                        <xs:element name="Diagnosticos" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Diagnostico"
                                                  maxOccurs="unbounded">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="CodigoCID10" type="xs:string"/>
                                                  <xs:element name="Descricao" type="xs:string"/>
                                                  <xs:element name="Tipo" type="xs:string"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Tratamentos" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Tratamento"
                                                  maxOccurs="unbounded">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="ID" type="xs:int"/>
                                                  <xs:element name="IdRegistoClinico" type="xs:int"/>
                                                  <xs:element name="Tipo" type="xs:string"/>
                                                  <xs:element name="Realizado">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="Sim"/>
                                                  <xs:enumeration value="Nao"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="ResumoMensal">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="NumeroTotalDeTransferenciasPorMotivo" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MotivoDetalhes" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Motivo" type="xs:string"/>
                                                  <xs:element name="Total" type="xs:int"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="NumeroTotalDeTransferenciasPorTipo" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="TipoDetalhes" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Tipo" type="xs:string"/>
                                                  <xs:element name="Total" type="xs:int"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="NumeroTotalDeTransferenciasPorHospital" minOccurs="0"
                                maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="HospitalDetalhes" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="NomeHospital" type="xs:string"/>
                                                  <xs:element name="Total" type="xs:int"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== luismorais14/PEI_2425/XML+XSD/relatorio_transferencias.xml
<Relatorio
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Transferencias.xsd" xsi:schemaLocation="http://www.MedSync.pt/Transferencias Transferencias.xsd">
	<HospitalDestino>
		<NomeHospital>Hospital Geral da Cidade</NomeHospital>
		<RegistosTransferencias>
			<CodigoPaciente>8822</CodigoPaciente>
			<DataTransferencia>2023-02-05T00:00:00.000Z</DataTransferencia>
			<Motivo>Consulta de segunda opinião</Motivo>
			<Diagnosticos>
				<Diagnostico>
					<CodigoCID10>D50</CodigoCID10>
					<Descricao>Anemia por deficiência de ferro</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>D50</CodigoCID10>
					<Descricao>Anemia por deficiência de ferro</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
			</Diagnosticos>
			<Tratamentos>
				<Tratamento>
					<ID>118763</ID>
					<IdRegistoClinico>73358</IdRegistoClinico>
					<Tipo>Colonoscopia</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>213306</ID>
					<IdRegistoClinico>73358</IdRegistoClinico>
					<Tipo>Cateterismo cardíaco</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
			</Tratamentos>
		</RegistosTransferencias>
	</HospitalDestino>
	<HospitalDestino>
		<NomeHospital>Hospital Geral da Cidade</NomeHospital>
		<RegistosTransferencias>
			<CodigoPaciente>70</CodigoPaciente>
			<DataTransferencia>2023-02-24T00:00:00.000Z</DataTransferencia>
			<Motivo>Exames complementares de diagnóstico</Motivo>
			<Diagnosticos>
				<Diagnostico>
					<CodigoCID10>E11</CodigoCID10>
					<Descricao>Diabetes mellitus não insulinodependente</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>R51</CodigoCID10>
					<Descricao>Cefaleia</Descricao>
					<Tipo>Secundario</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>G40</CodigoCID10>
					<Descricao>Epilepsia</Descricao>
					<Tipo>Secundario</Tipo>
				</Diagnostico>
			</Diagnosticos>
			<Tratamentos>
				<Tratamento>
					<ID>271607</ID>
					<IdRegistoClinico>141773</IdRegistoClinico>
					<Tipo>Imobilização de fratura</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>271607</ID>
					<IdRegistoClinico>141773</IdRegistoClinico>
					<Tipo>Imobilização de fratura</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>253393</ID>
					<IdRegistoClinico>246643</IdRegistoClinico>
					<Tipo>Teste de função hepática</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
			</Tratamentos>
		</RegistosTransferencias>
	</HospitalDestino>
	<HospitalDestino>
		<NomeHospital>Hospital Santa Maria</NomeHospital>
		<RegistosTransferencias>
			<CodigoPaciente>1811</CodigoPaciente>
			<DataTransferencia>2023-02-21T00:00:00.000Z</DataTransferencia>
			<Motivo>Exames complementares de diagnóstico</Motivo>
			<Diagnosticos>
				<Diagnostico>
					<CodigoCID10>F32</CodigoCID10>
					<Descricao>Episódios depressivos</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>J45</CodigoCID10>
					<Descricao>Asma</Descricao>
					<Tipo>Secundario</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>R51</CodigoCID10>
					<Descricao>Cefaleia</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
			</Diagnosticos>
			<Tratamentos>
				<Tratamento>
					<ID>158434</ID>
					<IdRegistoClinico>98069</IdRegistoClinico>
					<Tipo>Exame de hormônios (TSH, T3, T4)</Tipo>
					<Realizado>Nao</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>158434</ID>
					<IdRegistoClinico>98069</IdRegistoClinico>
					<Tipo>Exame de hormônios (TSH, T3, T4)</Tipo>
					<Realizado>Nao</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>244531</ID>
					<IdRegistoClinico>203679</IdRegistoClinico>
					<Tipo>Fisioterapia</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
			</Tratamentos>
		</RegistosTransferencias>
	</HospitalDestino>
	<HospitalDestino>
		<NomeHospital>Hospital de Coração</NomeHospital>
		<RegistosTransferencias>
			<CodigoPaciente>2481</CodigoPaciente>
			<DataTransferencia>2023-02-24T00:00:00.000Z</DataTransferencia>
			<Motivo>Consulta de segunda opinião</Motivo>
			<Diagnosticos>
				<Diagnostico>
					<CodigoCID10>S06</CodigoCID10>
					<Descricao>Traumatismo intracraniano</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>S06</CodigoCID10>
					<Descricao>Traumatismo intracraniano</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>T78</CodigoCID10>
					<Descricao>Reações adversas a alimentos não especificados</Descricao>
					<Tipo>Secundario</Tipo>
				</Diagnostico>
			</Diagnosticos>
			<Tratamentos>
				<Tratamento>
					<ID>104703</ID>
					<IdRegistoClinico>9754</IdRegistoClinico>
					<Tipo>Salbutamol inalatório</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>130277</ID>
					<IdRegistoClinico>9754</IdRegistoClinico>
					<Tipo>Exame de sangue</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>104703</ID>
					<IdRegistoClinico>9754</IdRegistoClinico>
					<Tipo>Salbutamol inalatório</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
			</Tratamentos>
		</RegistosTransferencias>
	</HospitalDestino>
	<HospitalDestino>
		<NomeHospital>Clínica São Paulo</NomeHospital>
		<RegistosTransferencias>
			<CodigoPaciente>7826</CodigoPaciente>
			<DataTransferencia>2023-02-05T00:00:00.000Z</DataTransferencia>
			<Motivo>Exames complementares de diagnóstico</Motivo>
			<Diagnosticos>
				<Diagnostico>
					<CodigoCID10>T78</CodigoCID10>
					<Descricao>Reações adversas a alimentos não especificados</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>O80</CodigoCID10>
					<Descricao>Parto único espontâneo</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>S06</CodigoCID10>
					<Descricao>Traumatismo intracraniano</Descricao>
					<Tipo>Secundario</Tipo>
				</Diagnostico>
			</Diagnosticos>
			<Tratamentos>
				<Tratamento>
					<ID>123528</ID>
					<IdRegistoClinico>160216</IdRegistoClinico>
					<Tipo>Dipirona 500mg</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>236686</ID>
					<IdRegistoClinico>203398</IdRegistoClinico>
					<Tipo>Punção lombar</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>236686</ID>
					<IdRegistoClinico>203398</IdRegistoClinico>
					<Tipo>Punção lombar</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
			</Tratamentos>
		</RegistosTransferencias>
	</HospitalDestino>
	<HospitalDestino>
		<NomeHospital>Hospital Geral da Cidade</NomeHospital>
		<RegistosTransferencias>
			<CodigoPaciente>2094</CodigoPaciente>
			<DataTransferencia>2023-02-14T00:00:00.000Z</DataTransferencia>
			<Motivo>Urgência médica</Motivo>
			<Diagnosticos>
				<Diagnostico>
					<CodigoCID10>H25</CodigoCID10>
					<Descricao>Catarata senil</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>M81</CodigoCID10>
					<Descricao>Osteoporose sem fratura patológica</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>M81</CodigoCID10>
					<Descricao>Osteoporose sem fratura patológica</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
			</Diagnosticos>
			<Tratamentos>
				<Tratamento>
					<ID>16219</ID>
					<IdRegistoClinico>271010</IdRegistoClinico>
					<Tipo>Exame de sangue</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>160254</ID>
					<IdRegistoClinico>271010</IdRegistoClinico>
					<Tipo>Teste de esforço</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>220310</ID>
					<IdRegistoClinico>271010</IdRegistoClinico>
					<Tipo>Raio-X</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
			</Tratamentos>
		</RegistosTransferencias>
	</HospitalDestino>
	<HospitalDestino>
		<NomeHospital>Hospital Geral da Cidade</NomeHospital>
		<RegistosTransferencias>
			<CodigoPaciente>1358</CodigoPaciente>
			<DataTransferencia>2023-02-26T00:00:00.000Z</DataTransferencia>
			<Motivo>Consulta de segunda opinião</Motivo>
			<Diagnosticos>
				<Diagnostico>
					<CodigoCID10>R51</CodigoCID10>
					<Descricao>Cefaleia</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>R51</CodigoCID10>
					<Descricao>Cefaleia</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>R51</CodigoCID10>
					<Descricao>Cefaleia</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
			</Diagnosticos>
			<Tratamentos>
				<Tratamento>
					<ID>53521</ID>
					<IdRegistoClinico>16334</IdRegistoClinico>
					<Tipo>Hemograma completo</Tipo>
					<Realizado>Nao</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>149311</ID>
					<IdRegistoClinico>16334</IdRegistoClinico>
					<Tipo>Imobilização de fratura</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
				<Tratamento>
					<ID>321993</ID>
					<IdRegistoClinico>16334</IdRegistoClinico>
					<Tipo>Metformina 850mg</Tipo>
					<Realizado>Sim</Realizado>
				</Tratamento>
			</Tratamentos>
		</RegistosTransferencias>
	</HospitalDestino>
	<HospitalDestino>
		<NomeHospital>Hospital São João</NomeHospital>
		<RegistosTransferencias>
			<CodigoPaciente>6041</CodigoPaciente>
			<DataTransferencia>2023-02-27T00:00:00.000Z</DataTransferencia>
			<Motivo>Consulta de segunda opinião</Motivo>
			<Diagnosticos>
				<Diagnostico>
					<CodigoCID10>L20</CodigoCID10>
					<Descricao>Dermatite atópica</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>L20</CodigoCID10>
					<Descricao>Dermatite atópica</Descricao>
					<Tipo>Principal</Tipo>
				</Diagnostico>
				<Diagnostico>
					<CodigoCID10>L20</CodigoCID10>
